services:
  postgres:
    image: postgres:16-alpine
    container_name: application_postgres
    environment:
      POSTGRES_USER: application_user
      POSTGRES_PASSWORD: application_pass
      POSTGRES_DB: application_db
    ports:
      - "5435:5432"
    volumes:
      - application_pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
    container_name: application_api
    environment:
      - PORT=3005
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=application_user
      - DB_PASSWORD=application_pass
      - DB_NAME=application_db
      - DB_SSLMODE=disable
      - JWT_SECRET=changeme-super-secret-key
    depends_on:
      - postgres
    ports:
      - "3005:3005"

volumes:
  application_pg_data:
