services:
  postgres:
    image: postgres:16-alpine
    container_name: program_postgres
    environment:
      POSTGRES_USER: program_user
      POSTGRES_PASSWORD: program_pass
      POSTGRES_DB: program_db
    ports:
      - "5434:5432"
    volumes:
      - program_pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
    container_name: program_api
    environment:
      - PORT=3004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=program_user
      - DB_PASSWORD=program_pass
      - DB_NAME=program_db
      - DB_SSLMODE=disable
      - JWT_SECRET=changeme-super-secret-key
    depends_on:
      - postgres
    ports:
      - "3004:3004"

volumes:
  program_pg_data:
